#+TITLE: Starter Kit Dired
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Dired

** Basic settings
#+name: dired-dwim
#+begin_src emacs-lisp
  (setq dired-dwim-target 1
	dired-isearch-filenames 'dwim
	dired-listing-switches "-v -AlR --group-directories-first --human-readable"
        dired-trivial-filenames "\\`\\.\\.?\\'\\|\\`#\\|\\`\\.")
#+end_src

** Dired-x
Loading Dired-X will automatically put on the hook ‘dired-extra-startup’ to
‘dired-mode-hook’ to get extra Dired features:
+ V -- run mail on folder (see ‘dired-bind-vm’)
+ I -- run info on file
+ N -- run man on file
+ F -- visit all marked files simultaneously
+ C-x M-o -- toggle omitting of files
+ M-( -- mark by Lisp expression

#+name: dired-x
#+begin_src emacs-lisp
  (defun my/load-dired-x () (load-library "dired-x"))
  (add-hook 'dired-load-hook #'my/load-dired-x)
#+end_src
** Key bindings
Also see [[./starter-kit-hydras.org][starter-kit-hydras.org]] for additional key bindings.

*** my/diredp-ediff
Taken from Dired+
See https://github.com/emacsmirror/dired-plus/blob/master/dired%2B.el

  "Compare file at cursor with file FILE2 using `ediff'.
FILE2 defaults to the file at the cursor as well.  If you enter just a
directory name for FILE2, then the file at the cursor is compared with
a file of the same name in that directory.  FILE2 is the second file
given to `ediff'; the file at the cursor is the first.
Try to guess a useful default value for FILE2, as follows:
 * If the mark is active, use the file at mark.
 * Else if the file at cursor is a autosave file or a backup file, use
   the corresponding base file.
 * Else if there is any backup file for the file at point, use the
   newest backup file for it.
 * Else use the file at point."
#+begin_src emacs-lisp
(defun my/diredp-ediff (file2)             ; Bound to `='
  (interactive (progn (require 'ediff)
                      (list (ediff-read-file-name ; In `ediff-util.el'.
                             (format "Compare %s with" (dired-get-filename t))
                             (dired-current-directory)
                             (let* ((file           (dired-get-filename))
                                    (file-sans-dir  (file-name-nondirectory file))
                                    (file-dir       (file-name-directory file))
                                    (file-at-mark   (and transient-mark-mode
                                                         mark-active
                                                         (save-excursion (goto-char (mark t))
                                                                         (dired-get-filename t t))))
                                    (last-backup    (file-newest-backup file)))
                               (cond
                                 (file-at-mark)
                                 ((auto-save-file-name-p file-sans-dir)
                                  (expand-file-name (substring file-sans-dir 1 -1) file-dir))
                                 ((backup-file-name-p file-sans-dir)
                                  (expand-file-name (file-name-sans-versions file-sans-dir) file-dir))
                                 (last-backup)
                                 (t file)))))))
  (ediff-files (dired-get-filename) file2)) ; In `ediff.el'.
#+end_src

*** my/dired-maybe-insert-subdir
#+name: my/dired-maybe-insert-subdir
#+begin_src emacs-lisp
  (defun my/dired-maybe-insert-subdir (dirname &optional
					    switches no-error-if-not-dir-p)
    (interactive
     (list (dired-get-filename)
	   (if current-prefix-arg
	       (read-string "Switches for listing: "
			    (or dired-subdir-switches dired-actual-switches)))))
    (let ((opoint (point)))
      (dired-maybe-insert-subdir dirname switches nil)
      (if (bound-and-true-p dired-hide-details-mode)
	  (recenter 1)
	(recenter 2))))
#+end_src

*** my/dired-mode-keys
#+name: dired-mode-hook-keys
#+begin_src emacs-lisp
  (defun my/dired-mode-keys ()
    "my keys for `dired'."
    (define-key dired-mode-map (kbd "<tab>")       'dired-hide-subdir)
    (define-key dired-mode-map (kbd "C-<tab>")     'dired-hide-all)
    (define-key dired-mode-map (kbd "i")           'my/dired-maybe-insert-subdir)
    (define-key dired-mode-map (kbd "e")           'my/diredp-ediff)
    (define-key dired-mode-map (kbd "C-M-i")       'dired-jump) ; like in org-mode
    (define-key dired-mode-map (kbd "<backspace>") 'dired-jump) ; like in Windows Explorer

    ;; use same keys with modifiers as speed keys
    (local-set-key "\M-." 'my/dired-maybe-insert-subdir))
  (add-hook 'dired-mode-hook #'my/dired-mode-keys)
#+end_src

** Initial Dired state
#+name: dired-mode-hook-setup
#+begin_src emacs-lisp
  ;;; Turn on omit from Dired-x.
  (setq dired-omit-size-limit nil) ; No maximum size for Omit.
  (setq-default dired-omit-mode t) ; Turn on Omit mode (buffer-local).

  ;;; Turn on Hide details mode.
  (add-hook 'dired-mode-hook #'dired-hide-details-mode)

  ;;; Turn on Truncate lines mode.
  (add-hook 'dired-mode-hook #'toggle-truncate-lines)
#+end_src
